import type { Reporter, Finding, ReportResult } from "../types.js";

interface GitHubConfig {
  token: string;
  owner: string;
  repo: string;
  labels?: string[];
}

export class GitHubReporter implements Reporter {
  name = "github";
  private config: GitHubConfig;

  constructor(config: GitHubConfig) {
    this.config = config;
  }

  async report(finding: Finding): Promise<ReportResult> {
    const { token, owner, repo, labels = ["proprio"] } = this.config;

    // Check for duplicate open issues
    const isDuplicate = await this.checkDuplicate(finding, token, owner, repo, labels);
    if (isDuplicate) {
      return { success: true, ref: "duplicate-skipped" };
    }

    const body = this.formatBody(finding);
    const allLabels = [...labels, finding.type];

    const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
        Accept: "application/vnd.github.v3+json",
      },
      body: JSON.stringify({
        title: `[proprio] ${finding.title}`,
        body,
        labels: allLabels,
      }),
    });

    if (!response.ok) {
      const err = await response.text();
      return { success: false, error: `GitHub API error ${response.status}: ${err}` };
    }

    const issue = (await response.json()) as { html_url: string };
    return { success: true, ref: issue.html_url };
  }

  private formatBody(finding: Finding): string {
    const severityEmoji = {
      critical: "🔴",
      warning: "🟡",
      info: "🔵",
    }[finding.severity];

    let body = `## ${severityEmoji} ${finding.severity.toUpperCase()} — ${finding.type}\n\n`;
    body += `**Confidence:** ${(finding.confidence * 100).toFixed(0)}%\n`;
    body += `**Analyzer:** ${finding.sourceAnalyzer}\n\n`;
    body += `### Description\n${finding.description}\n\n`;

    if (finding.evidence.length > 0) {
      body += `### Evidence\n| Metric | Value | Context |\n|--------|-------|--------|\n`;
      for (const e of finding.evidence) {
        body += `| ${e.metric} | ${e.value} | ${e.context} |\n`;
      }
      body += "\n";
    }

    if (finding.suggestion) {
      body += `### Suggestion\n${finding.suggestion}\n\n`;
    }

    if (finding.escalatedToLLM && finding.llmReasoning) {
      body += `### LLM Analysis\n${finding.llmReasoning}\n\n`;
    }

    if (finding.fix) {
      const fix = finding.fix;
      body += `### Proposed Fix\n\n`;
      body += `**File:** \`${fix.file}\`\n`;
      body += `**Confidence:** ${(fix.confidence * 100).toFixed(0)}%`;
      if (fix.breaking) body += ` ⚠️ Potentially breaking`;
      body += `\n\n`;
      body += `${fix.explanation}\n\n`;
      body += `\`\`\`diff\n`;
      for (const diff of fix.diff) {
        body += `# Lines ${diff.startLine}-${diff.endLine}\n`;
        for (const line of diff.oldCode.split("\n")) {
          body += `- ${line}\n`;
        }
        for (const line of diff.newCode.split("\n")) {
          body += `+ ${line}\n`;
        }
      }
      body += `\`\`\`\n\n`;
    }

    body += `---\n*Generated by [proprio](https://github.com/vanthuyphan/proprio)*`;
    return body;
  }

  private async checkDuplicate(
    finding: Finding,
    token: string,
    owner: string,
    repo: string,
    labels: string[],
  ): Promise<boolean> {
    const labelQuery = labels.map((l) => `label:"${l}"`).join("+");
    const query = encodeURIComponent(`repo:${owner}/${repo} is:issue is:open ${labelQuery} "${finding.title}" in:title`);

    const response = await fetch(`https://api.github.com/search/issues?q=${query}&per_page=1`, {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github.v3+json",
      },
    });

    if (!response.ok) return false;
    const data = (await response.json()) as { total_count: number };
    return data.total_count > 0;
  }
}
